# ARRAY

An array can be defined as a storage or container or similar items place in contiguos locations

# Array Implementation in Python

1 Python Array Module

2 Python Numpy Array

# Homogeneous Arrays

Homogeneos arrays will contain the elements of same data type.

# Hetrogeneous Arrays

Hetrogeneous arrays arrays will contain the elements  that may not be of same data type

# Implementation

In [1]:
#Python Array Module
import array as myarray

# TypeCodes Available for the array modules for various data Types

1. 'i'-Integer type-2
2. 'f'-Float type-4
3. 'd'-Double type-8
4. 'u'-unicode character-2

In [2]:
#Create An Array
arr=myarray.array('i',[1,2,3])
arr1=myarray.array('d',[1.0,2.1,2.4,2.5,2.6])
arr2=myarray.array('u',['a','b','c','d'])

#typecodes
print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)

#fiest look at the array
print(arr)
print(arr1)
print(arr2)

i
d
u
array('i', [1, 2, 3])
array('d', [1.0, 2.1, 2.4, 2.5, 2.6])
array('u', 'abcd')


In [3]:
#print the length of an array
print(len(arr))
print(len(arr1))
print(len(arr2))

3
5
4


In [6]:
#Print the element of array
for i in range(0,len(arr)):
    print(arr[i],end=" ")
print("\n")

for i in range(0,len(arr1)):
    print(arr1[i],end=" ")
print("\n")

for i in range(0,len(arr2)):
    print(arr2[i],end=" ")    

1 2 3 

1.0 2.1 2.4 2.5 2.6 

a b c d 

# What is Indexing?

For Array of the length n ,yhe indexing will be the position which each element is placed in  an array.To be able to access the elements in an array.indexing comes in handy.For an array of lenth n,the indexing start from 0 and end at n-1

In [7]:
#Assessing Elements froman array using index value
x=list(range(1,100))
new_array=myarray.array('i',x)

#printing yhe array
for i in range(0,len(new_array)):
    print(new_array[i],end=" ")
print("\n")

#Accessing the element at index "25"
print(new_array[25])

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

26


# Insert

In [16]:
#Create an array
new_arr = myarray.array('i',[3,4,5,6,7,8,9,10])
for i in range(0,len(new_arr)):
    print(new_arr[i],end=" ")
print("\n")

#Adding Elements in an array using insert
new_arr.insert(0,2)
new_arr.insert(0,1)

#printing the new array
for i in range(0,len(new_arr)):
    print(new_arr[i],end=" ")
print("\n")

#Adding Elements in an array using append
new_arr.append(11)
for i in range(0,len(new_arr)):
    print(new_arr[i],end=" ")
print("\n")

3 4 5 6 7 8 9 10 

1 2 3 4 5 6 7 8 9 10 

1 2 3 4 5 6 7 8 9 10 11 



# Update

In [27]:
#Create the Array
new_array=myarray.array('i',[1,2,2,4,5])

#printing array
for i in range(0,len(new_array)):
    print(new_array[i],end=" ")
print("\n")

#Update the element of array
new_array[2]=3
for i in range(0,len(new_array)):
    print(new_array[i],end=" ")
print("\n")


1 2 2 4 5 

1 2 3 4 5 



# Delete

In [28]:
#delete elements in an array using pop
#1 2 3 4 5
new_array.pop(4)

for i in range(0,len(new_array)):
    print(new_array[i],end=" ")
print("\n")

#delete elements in an array using remove
new_array.remove(4)

for i in range(0,len(new_array)):
    print(new_array[i],end=" ")
print("\n")

1 2 3 4 

1 2 3 



# Slicing

Slicing is the process of getting a sequence from the data structure which will will have a starting index and an ending index.
Since Python arrays provide indexing slicing operations provide extension of arrays.

In [33]:
#slicing operation i an array
x=list(range(0,100,3))
arr=myarray.array('i',x)

#slicing operation
arr0=arr[10:20]
for i in range(0,len(arr0)):
    print(arr0[i],end=" ")
print('\n')    
#Negative index 
arr1=arr[10:-10]
for i in range(0,len(arr1)):
    print(arr1[i],end=" ")
print('\n')     
#Reversing the order using slicing
arr2=arr[::-1]
for i in range(0,len(arr2)):
    print(arr2[i],end=" ")

30 33 36 39 42 45 48 51 54 57 

30 33 36 39 42 45 48 51 54 57 60 63 66 69 

99 96 93 90 87 84 81 78 75 72 69 66 63 60 57 54 51 48 45 42 39 36 33 30 27 24 21 18 15 12 9 6 3 0 

# Search

In [35]:
#Search operation in an array using index
x=list(range(0,10000,2))
search_array=myarray.array('i',x)

#print first 10 element of an array
for i in range(0,len(search_array[0:10])):
    print(search_array[i],end=" ")
print("\n")

#Search the number 16 in an array
index=search_array.index(16)
res=search_array[index]
print(index,res)

0 2 4 6 8 10 12 14 16 18 

8 16


# Sort

In [44]:
#Sorting Operations
sort_array=myarray.array('i',[5,4,3,6,7,8,9,2,1])
sorted_array=sort_array.tolist()

#ascending order
sorted_array.sort()
print(sorted_array)

#descending order
sorted_array.sort(reverse=True)
print(sorted_array)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


# Numpy Arrays

In [45]:
#import numpy
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [54]:
#create an array with all zero
zeros=np.zeros((2,2))
print(zeros)
print("\n")

#create an array with all ones
ones=np.ones((2,2))
print(ones)
print('\n')

#create an array with constant
const=np.full((2,2),5)
print(const)
print("\n")

#create an identity matrix
iden=np.eye(2)
print(iden)
print("\n")

#create an array with random values
random=np.random.random((2,2))
print(random)
print("\n")

[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]]


[[5 5]
 [5 5]]


[[1. 0.]
 [0. 1.]]


[[0.09070584 0.7659541 ]
 [0.3961496  0.9302613 ]]




# 0D,1D,2D,3D

In [63]:
#0 Dimensional Array
zerod=np.array(1)
print(zerod)
print('\n')

#1 Dimensional Array
oned=np.array([1,1])
print(oned)
print('\n')

#2 Dimensional Array
twod=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(twod)
print('\n')

#3 Dimensional Array
threed=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(threed)
print('\n')

#Multi Dimensional Array
multid=np.array([1,2,3,4,5],ndmin=5)
print(multid)
print('\n')

1


[1 1]


[[1 2 3 4 5]
 [1 2 3 4 5]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[[[[1 2 3 4 5]]]]]




In [65]:
#Check Dimension
print(zerod.ndim)
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)
print(multid.ndim)

0
1
2
3
5


In [69]:
#CRUD Operation in numpy Arrays

#reading from numpy arrays
sample_array=np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0,len(sample_array)):
    print(sample_array[i],end=" ")
print("\n")    


#Updateing element in a numpy array we make use indexing here
sample_array[9]=100
print(sample_array)
print("\n")

#deleting elements in a numpy array
sample_array=np.delete(sample_array,9)
print(sample_array)

1 2 3 4 5 6 7 8 9 10 

[  1   2   3   4   5   6   7   8   9 100]


[1 2 3 4 5 6 7 8 9]


In [71]:
#searching element in an numpy array
x=list(range(0,100,5))
sample_search_array=np.array(x)

#Searching the element 20
res=np.where(sample_search_array==20)
print(res)

#checking if the returning index is true
print(sample_search_array[4])

(array([4], dtype=int64),)
20


In [72]:
#Sorting elements in a numpy array
sample_sort_array=np.array([1,3,5,7,9,2,4,6,8,10])

#sorting the numpy array using sort
sort=np.sort(sample_sort_array)
print(sort)

[ 1  2  3  4  5  6  7  8  9 10]


In [79]:
#Mathematical Operation
a=np.array([[1,2,3]],dtype=np.int64)
b=np.array([[4,5,6]],dtype=np.int64)

#Addition two numpy array
addition=np.add(a,b)
print(addition)
print("\n")
#Substraction two numpy array
Substraction=np.subtract(a,b)
print(Substraction)
print("\n")
#Multiplication two numpy array
Multiplication=np.multiply(a,b)
print(Multiplication)
print("\n")
#Division two numpy array
Division=np.divide(a,b)
print(Division)
print("\n")
#Square root numpy array
sqrta=np.sqrt(a)
sqrtb=np.sqrt(b)
print(sqrta)
print(sqrtb)
print("\n")

#Transpose ofnumpy array
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
transpose=np.transpose(x)
print(x)
print("\n")
print(transpose)

[[5 7 9]]


[[-3 -3 -3]]


[[ 4 10 18]]


[[0.25 0.4  0.5 ]]


[[1.         1.41421356 1.73205081]]
[[2.         2.23606798 2.44948974]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 4 7]
 [2 5 8]
 [3 6 9]]
